<a href="https://colab.research.google.com/github/codeKrantz/PyTorch-for-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.11.0+cu128


In [4]:
#!nvidia-smi

### Tensors

In [6]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
scalar.item() #as an int

7

In [11]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [13]:
vector.shape

torch.Size([2])

In [ ]:
#2x1

In [15]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
MATRIX.ndim

2

In [17]:
MATRIX[0]

tensor([7, 8])

In [18]:
MATRIX.shape

torch.Size([2, 2])

In [22]:
#TENSOR
TENSOR = torch.tensor([[[1,7,3],
                        [3,4,5],
                       [2,4,6]]])
TENSOR

tensor([[[1, 7, 3],
         [3, 4, 5],
         [2, 4, 6]]])

In [23]:
TENSOR.ndim

3

In [24]:
TENSOR.shape #we are now in 3 demsinions: starting at the 0th

torch.Size([1, 3, 3])

In [25]:
TENSOR[0]

tensor([[1, 7, 3],
        [3, 4, 5],
        [2, 4, 6]])

In [26]:
#Practice: create a custom tensor and pay around with seeing its demsionsions, shape, ect...
practice = torch.tensor([[[1,3,4,5],[2,3,4,6],[4,4,4,4]],[[1,1,1,2],[3,4,5,6],[2,2,2,6]]])
practice

tensor([[[1, 3, 4, 5],
         [2, 3, 4, 6],
         [4, 4, 4, 4]],

        [[1, 1, 1, 2],
         [3, 4, 5, 6],
         [2, 2, 2, 6]]])

In [27]:
practice.ndim

3

In [28]:
practice.shape

torch.Size([2, 3, 4])