<a href="https://colab.research.google.com/github/codeKrantz/PyTorch-for-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.11.0+cpu


In [2]:
#!nvidia-smi

### Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item() #as an int

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#2x1

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,7,3],
                        [3,4,5],
                       [2,4,6]]])
TENSOR

tensor([[[1, 7, 3],
         [3, 4, 5],
         [2, 4, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape #we are now in 3 demsinions: starting at the 0th

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 7, 3],
        [3, 4, 5],
        [2, 4, 6]])

#### Practice

In [18]:
#Practice: create a custom tensor and pay around with seeing its demsionsions, shape, ect...
practice = torch.tensor([[[1,3,4,5],[2,3,4,6],[4,4,4,4]],[[1,1,1,2],[3,4,5,6],[2,2,2,6]]])
practice

tensor([[[1, 3, 4, 5],
         [2, 3, 4, 6],
         [4, 4, 4, 4]],

        [[1, 1, 1, 2],
         [3, 4, 5, 6],
         [2, 2, 2, 6]]])

In [19]:
practice.ndim

3

In [20]:
practice.shape

torch.Size([2, 3, 4])

#Random Tensors

Allow networks to learn to better represent the data

In [24]:
#Creating a tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5376, 0.8405, 0.9630, 0.6889],
        [0.0744, 0.2593, 0.9525, 0.3218],
        [0.1584, 0.2872, 0.5559, 0.4730]])

In [25]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with a similar shape to an image tensor

In [26]:
random_image_size_tensor = torch.rand(size=(3,224,224)) #color channel,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

####Practice

In [ ]:
#Practice: create custom random tensor

In [27]:
practice = torch.rand(3,5,6)
practice

tensor([[[0.1096, 0.5123, 0.1870, 0.6899, 0.8983, 0.3806],
         [0.5033, 0.6075, 0.1619, 0.0363, 0.0844, 0.1157],
         [0.9911, 0.6970, 0.6646, 0.6209, 0.2402, 0.6840],
         [0.3717, 0.4035, 0.8698, 0.4655, 0.8082, 0.3099],
         [0.9524, 0.9996, 0.5266, 0.3002, 0.4313, 0.3566]],

        [[0.7298, 0.1050, 0.0331, 0.8823, 0.0094, 0.5686],
         [0.7395, 0.7674, 0.4171, 0.4280, 0.2677, 0.3637],
         [0.9441, 0.3505, 0.3246, 0.4775, 0.5982, 0.0437],
         [0.2138, 0.0636, 0.4375, 0.6493, 0.8386, 0.4454],
         [0.5947, 0.8856, 0.1303, 0.4560, 0.1591, 0.6624]],

        [[0.4897, 0.5005, 0.8630, 0.2885, 0.3120, 0.8149],
         [0.1000, 0.3723, 0.3928, 0.0497, 0.0561, 0.4721],
         [0.2123, 0.4181, 0.7126, 0.5955, 0.5754, 0.2260],
         [0.6031, 0.8212, 0.1822, 0.8926, 0.5162, 0.1652],
         [0.5713, 0.5123, 0.3178, 0.7749, 0.1752, 0.0573]]])

In [28]:
practice.ndim

3

In [29]:
practice.shape

torch.Size([3, 5, 6])