<a href="https://colab.research.google.com/github/codeKrantz/PyTorch-for-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.11.0+cpu


In [ ]:
#!nvidia-smi

### Tensors

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item() #as an int

7

In [ ]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#2x1

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#TENSOR
TENSOR = torch.tensor([[[1,7,3],
                        [3,4,5],
                       [2,4,6]]])
TENSOR

tensor([[[1, 7, 3],
         [3, 4, 5],
         [2, 4, 6]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape #we are now in 3 demsinions: starting at the 0th

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 7, 3],
        [3, 4, 5],
        [2, 4, 6]])

#### Practice

In [ ]:
#Practice: create a custom tensor and pay around with seeing its demsionsions, shape, ect...
practice = torch.tensor([[[1,3,4,5],[2,3,4,6],[4,4,4,4]],[[1,1,1,2],[3,4,5,6],[2,2,2,6]]])
practice

tensor([[[1, 3, 4, 5],
         [2, 3, 4, 6],
         [4, 4, 4, 4]],

        [[1, 1, 1, 2],
         [3, 4, 5, 6],
         [2, 2, 2, 6]]])

In [ ]:
practice.ndim

3

In [ ]:
practice.shape

torch.Size([2, 3, 4])

#Random Tensors

Allow networks to learn to better represent the data

In [ ]:
#Creating a tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0672, 0.1224, 0.5219, 0.8297],
        [0.2078, 0.3939, 0.6952, 0.1732],
        [0.2718, 0.1061, 0.4899, 0.8697]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#Create a random tensor with a similar shape to an image tensor

In [ ]:
random_image_size_tensor = torch.rand(size=(3,224,224)) #color channel,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

####Practice

In [ ]:
#Practice: create custom random tensor

In [ ]:
practice = torch.rand(3,5,6)
practice

tensor([[[0.2532, 0.3519, 0.9959, 0.2074, 0.8410, 0.1621],
         [0.6782, 0.7890, 0.6998, 0.2814, 0.9838, 0.1034],
         [0.2051, 0.8898, 0.9548, 0.1389, 0.2243, 0.1885],
         [0.1416, 0.6898, 0.7092, 0.6203, 0.4905, 0.3131],
         [0.9234, 0.9685, 0.3442, 0.9987, 0.4880, 0.8704]],

        [[0.7593, 0.2803, 0.8862, 0.5341, 0.0974, 0.9695],
         [0.1982, 0.7849, 0.8946, 0.9087, 0.7078, 0.3729],
         [0.1144, 0.0504, 0.8880, 0.5064, 0.4003, 0.6834],
         [0.4514, 0.8492, 0.9506, 0.0236, 0.4311, 0.5867],
         [0.3853, 0.1350, 0.7052, 0.4998, 0.3694, 0.5916]],

        [[0.5750, 0.6141, 0.2918, 0.6266, 0.4953, 0.2905],
         [0.6759, 0.8172, 0.6353, 0.3058, 0.4362, 0.6475],
         [0.4595, 0.9919, 0.4841, 0.7735, 0.3510, 0.3144],
         [0.7009, 0.7175, 0.0391, 0.7559, 0.3879, 0.0254],
         [0.2327, 0.9151, 0.5829, 0.1541, 0.3124, 0.2799]]])

In [ ]:
practice.ndim

3

In [ ]:
practice.shape

torch.Size([3, 5, 6])

### Zeros and Ones

In [ ]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

##Creating range of tensors and tensors-like

In [ ]:
torch.range(0,10) #not removed yet

/tmp/ipykernel_15697/276358740.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10) #not removed yet


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(1,11) #will replace range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
one_to_ten = torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros


tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Practice

In [ ]:
#Practice: build a tensors of zeros using arange
my_list = torch.arange(1,100,2)
my_list

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
        37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71,
        73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [ ]:
my_zeros = torch.zeros_like(my_list)
my_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0])

## Tensor datatypes
One of the 3 areas where erros occure
1. Wrong datatype
2. Wrong shaope
3. Not of the right device

In [ ]:
#Float 32

In [ ]:
#The parameters of a tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                                dtype=None, #The datatype
                                device=None, #for gpu set to cuda, erros occure if data is not on same type of device
                                requires_grad=False) #Weather or not to track gradients

float_32_tensor.dtype

torch.float32

In [ ]:
#can convert a tensor to a diffent dtype
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

###Practice

In [ ]:
#Practice: construct a tensor with a differnt dtype than before

In [ ]:
complex_tensor = float_32_tensor.type(torch.complex32)
complex_tensor

/tmp/ipykernel_15697/2105027858.py:1: UserWarning: ComplexHalf support is experimental and many operators don't support it yet. (Triggered internally at /pytorch/aten/src/ATen/EmptyTensor.cpp:54.)
  complex_tensor = float_32_tensor.type(torch.complex32)


tensor([3.+0.j, 6.+0.j, 9.+0.j], dtype=torch.complex32)

#Operations

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

#Getting Information

In [ ]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.9077, 0.8859, 0.5109, 0.6702],
        [0.3059, 0.9369, 0.6361, 0.1446],
        [0.3038, 0.6041, 0.5192, 0.3330]])

In [ ]:
print(some_tensor)
print(f"Datatype: {some_tensor.dtype}")
print(f"Shape: {some_tensor.shape}")
print(f"Device: {some_tensor.device}")

tensor([[0.9077, 0.8859, 0.5109, 0.6702],
        [0.3059, 0.9369, 0.6361, 0.1446],
        [0.3038, 0.6041, 0.5192, 0.3330]])
Datatype: torch.float32
Shape: torch.Size([3, 4])
Device: cpu


### Tensor Operations

Include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [ ]:
#Addition
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply
tensor = tensor * 10
tensor

tensor([10, 20, 30])

In [ ]:
#Subtract
tensor - 10

tensor([ 0, 10, 20])

In [ ]:
#In built functions
tensor = torch.mul(tensor, 10)
tensor

tensor([1000, 2000, 3000])

### Matrix Multiplication

> 2 ways: element and matrix




In [ ]:
#AKA the dot product

#element
print(tensor, "*", tensor)
print(f"{tensor*tensor}")

tensor([1000, 2000, 3000]) * tensor([1000, 2000, 3000])
tensor([1000000, 4000000, 9000000])


In [ ]:
#matrix mult
torch.matmul(tensor,tensor)

tensor(14000000)

In [ ]:
%%time
tensor = torch.tensor([1,2,3])
value = 0
#for a vector only
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.96 ms, sys: 0 ns, total: 1.96 ms
Wall time: 1.72 ms


In [ ]:
%%time
#Much Faster!!!
torch.matmul(tensor,tensor)


CPU times: user 357 µs, sys: 19 µs, total: 376 µs
Wall time: 307 µs


tensor(14)

##Finding min, max, mean, sum, ect...

In [ ]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.max(x), torch.min(x)

(tensor(90), tensor(0))

In [ ]:
#wants a float or a complex tensor NOT a long dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32)

(tensor(45.), tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [ ]:
#can call the method from torch or the tensor
x.max(), torch.max(x)

(tensor(90), tensor(90))

### Challenge


In [ ]:
#Challenge: Find positional min and max, argmin and argmax

#### They return the index of the max or min value

In [ ]:
#useful for softmax function
torch.argmax(x)

tensor(9)

In [ ]:
torch.argmin(x)

tensor(0)

## Reshapping, stacking, squeezing, and unsqueezing tensors

In [ ]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
#Reshape, add an extra dimension MUST BE COMPATBLE WITH ORIGINAL SIZE
x_reshape = x.reshape(9,1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
#Change the view - shares the memory as the orignial tensor
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#What if z changes?
z[:, 0] = 5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

##

In [ ]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#Squeeze - removes all single dimensions
x = torch.zeros(2, 1, 2, 1, 2)
x.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x)
y.size()
torch.Size([2, 2, 2])
y = torch.squeeze(x, 0)
y.size()
torch.Size([2, 1, 2, 1, 2])
y = torch.squeeze(x, 1)
y.size()
torch.Size([2, 2, 1, 2])
y = torch.squeeze(x, (1, 2, 3))
torch.Size([2, 2, 2])

torch.Size([2, 2, 2])

In [ ]:
x_reshape.squeeze().shape

torch.Size([9])

In [ ]:
#Unsqueeze - adds a single dimensions at a specific dimensions of a tensor
print(f"Previouse: {x.squeeze()}")
print(f"Shape: {x.squeeze().shape}")

x = x.squeeze()

x_unsqueezed = x.unsqueeze(dim=0)
x_unsqueezed

Previouse: tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])
Shape: torch.Size([2, 2, 2])


tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]])

In [ ]:
#torch.permute - rearranges dimensions in a specified order
x_original = torch.rand(size=(224,224,3)) #image data standards

#Permute to rearrange the axis order
x_permuted = x_original.permute(2,0,1) #Shifts the axis to a new location

#Will have the same place in memory
print(f"Old: {x_original.shape}")
print(f"New: {x_permuted.shape}")

Old: torch.Size([224, 224, 3])
New: torch.Size([3, 224, 224])


## Indexing
selecting data

In [ ]:
#Will be similar to Numpy
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
#Indexing on new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#on the middle bracket
x[0][0], x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
#last dim
x[0,2,2]

tensor(9)

In [ ]:
#Use : to select all of a dim
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
#More practice
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
#Challenge: return 3,6,9

In [ ]:
#the sole dimension, all rows, last col
x[0,:,2]

tensor([3, 6, 9])

##Pytorch and NumPy

* Data in NumPy -> Pytorch tensor
* tensor -> NumPy

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

#Same data but differnt data type by default
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Change the value of array, tensor difference?
array = array + 1

#Will not change the tensor
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
#Tensor -> NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change tensor, array change?
tensor = tensor + 1

#Does not change
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility
* Taking the random out of random

In [ ]:
#Random numbers -> operations -> update random numbers and make them better -> again...
torch.rand(3,3)

tensor([[6.1459e-01, 8.3573e-01, 7.0125e-01],
        [9.0218e-01, 9.9575e-02, 5.1755e-01],
        [8.0263e-01, 2.2080e-01, 7.3093e-04]])

In [ ]:
#Random seeds reduce some of the overal randomness by flavoring it
import torch
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.4917, 0.9423, 0.1951, 0.6632],
        [0.1217, 0.4931, 0.0878, 0.9967],
        [0.5701, 0.9715, 0.1844, 0.5871]])
tensor([[0.0421, 0.4580, 0.2441, 0.7737],
        [0.2851, 0.0520, 0.0941, 0.2230],
        [0.4656, 0.4636, 0.8568, 0.6106]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#random but reproducible tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

#need to reset the seed after each use
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running and Getting a GPU for tensor work
* Colab (pro versions avalible)
* Your own Device GPU
* Cloud computing: GCP, AWS, Azure ...

In [2]:
#Review Pytorch set up documentation (install statements)
import torch

In [3]:
#Checking for GPU access
torch.cuda.is_available()

True

In [ ]:
#Best Practice: Device agnostic code, GPU may not exist on other devices
device = "cuda" if torch.cuda.is_available() else "cpu"

In [4]:
#Count GPUs
torch.cuda.device_count()

1

##