<a href="https://colab.research.google.com/github/codeKrantz/PyTorch-for-deep-learning/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Fundamentals

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)


2.11.0+cpu


In [2]:
#!nvidia-smi

### Tensors

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item() #as an int

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#2x1

In [10]:
#MATRIX
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#TENSOR
TENSOR = torch.tensor([[[1,7,3],
                        [3,4,5],
                       [2,4,6]]])
TENSOR

tensor([[[1, 7, 3],
         [3, 4, 5],
         [2, 4, 6]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape #we are now in 3 demsinions: starting at the 0th

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 7, 3],
        [3, 4, 5],
        [2, 4, 6]])

#### Practice

In [18]:
#Practice: create a custom tensor and pay around with seeing its demsionsions, shape, ect...
practice = torch.tensor([[[1,3,4,5],[2,3,4,6],[4,4,4,4]],[[1,1,1,2],[3,4,5,6],[2,2,2,6]]])
practice

tensor([[[1, 3, 4, 5],
         [2, 3, 4, 6],
         [4, 4, 4, 4]],

        [[1, 1, 1, 2],
         [3, 4, 5, 6],
         [2, 2, 2, 6]]])

In [19]:
practice.ndim

3

In [20]:
practice.shape

torch.Size([2, 3, 4])

#Random Tensors

Allow networks to learn to better represent the data

In [21]:
#Creating a tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6009, 0.3227, 0.6815, 0.4049],
        [0.3519, 0.6540, 0.6285, 0.6700],
        [0.7846, 0.5864, 0.4133, 0.8249]])

In [22]:
random_tensor.ndim

2

In [23]:
#Create a random tensor with a similar shape to an image tensor

In [24]:
random_image_size_tensor = torch.rand(size=(3,224,224)) #color channel,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

####Practice

In [25]:
#Practice: create custom random tensor

In [26]:
practice = torch.rand(3,5,6)
practice

tensor([[[0.4049, 0.1229, 0.2999, 0.0877, 0.4223, 0.7231],
         [0.5059, 0.7665, 0.7586, 0.2275, 0.1100, 0.6339],
         [0.8105, 0.9078, 0.5527, 0.8613, 0.4568, 0.1691],
         [0.9964, 0.0049, 0.6602, 0.0836, 0.2395, 0.9430],
         [0.3353, 0.2637, 0.6643, 0.8642, 0.5768, 0.4676]],

        [[0.9371, 0.5256, 0.1556, 0.6846, 0.8336, 0.6009],
         [0.6748, 0.2144, 0.2871, 0.3744, 0.8554, 0.5925],
         [0.6608, 0.5096, 0.0345, 0.1717, 0.5579, 0.2216],
         [0.1359, 0.1666, 0.6584, 0.4884, 0.9082, 0.2247],
         [0.0887, 0.5594, 0.3578, 0.7189, 0.1673, 0.7261]],

        [[0.0714, 0.0841, 0.0269, 0.0571, 0.4025, 0.3616],
         [0.7833, 0.7512, 0.8624, 0.3011, 0.8912, 0.7009],
         [0.7778, 0.8627, 0.7495, 0.4458, 0.2702, 0.7210],
         [0.2483, 0.9889, 0.0243, 0.3484, 0.3711, 0.7383],
         [0.7435, 0.5784, 0.0236, 0.7967, 0.0140, 0.1160]]])

In [27]:
practice.ndim

3

In [28]:
practice.shape

torch.Size([3, 5, 6])

### Zeros and Ones

In [29]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [31]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [32]:
#Ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
ones.dtype

torch.float32